version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: finpilot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finpilot
    ports:
      - "5433:5432"

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  banking-service:
    build: ./banking-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ai-service

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - banking-service
